In [1]:
import numpy as np
import os
current_directory = os.getcwd()
print(current_directory) 



/mnt/c/WINDOWS/system32


In [3]:
A = np.array([
    ['a','b','c'],
    ['d','e','f'],
    ['g','h','i']
    
]
)

In [4]:
print(A)

[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]


In [5]:
A.ndim

2

In [6]:
A.shape

(3, 3)

In [7]:
A.max

<function ndarray.max>

In [16]:
B = np.arange(5)
print(B)

[0 1 2 3 4]


In [14]:
B+10

array([10, 11, 12, 13, 14])

In [19]:
#Broadcasting and Vectorised Operations
a = np.arange(4)

In [20]:
a

array([0, 1, 2, 3])

In [21]:
a+10

array([10, 11, 12, 13])

In [22]:
a*10

array([ 0, 10, 20, 30])

In [24]:
a+=100

In [25]:
a

array([200, 201, 202, 203])

In [26]:
l = [0,1,2,3]

In [27]:
[i*10 for i in l]

[0, 10, 20, 30]

In [29]:
a = np.arange(4)

In [31]:
b = np.array([10,10,10,10])

In [32]:
a+b

array([10, 11, 12, 13])

In [33]:
a*b

array([ 0, 10, 20, 30])

In [34]:
#Boolean Arrays

In [35]:
a = np.arange(4)

In [36]:
a

array([0, 1, 2, 3])

In [40]:
a[[0,-1]]

array([0, 3])

In [41]:
a[[True,False,False,True]]
#Select if a is true

array([0, 3])

In [44]:
a>=2
#Select if value of a>=2

array([False, False,  True,  True])

In [46]:
a[a>=2]
#Make array of a if a>=2

array([2, 3])

In [49]:
a.mean()

1.5

In [51]:
a[a>a.mean()]
#Select and build array of a if they are greatr than mean

array([2, 3])

In [52]:
a[~(a> a.mean())]
  #NOt greater than mean

array([0, 1])

In [53]:
a[(a==0)|(a==1)]

array([0, 1])

In [55]:
a[(a<=2) & (a%2==0)]

array([0, 2])

In [65]:
A = np.random.randint(100, size =(3,3))

In [66]:
A

array([[84, 33, 48],
       [68, 45, 17],
       [64, 20, 32]])

In [67]:
A[np.array([
    [True, False, True],
    [False,True,False],
    [True,False,True]
])]

array([84, 48, 45, 64, 32])

In [68]:
A>30

array([[ True,  True,  True],
       [ True,  True, False],
       [ True, False,  True]])

In [69]:
A[A>30]

array([84, 33, 48, 68, 45, 64, 32])

In [70]:
#Linear Algebra

In [74]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [76]:
#Perforance

In [78]:
B = np.array([
    

    [6,5],
    [4,3],
    [2,1]
])

In [79]:
A.dot(B) # Dot

array([[20, 14],
       [56, 41],
       [92, 68]])

In [80]:
A@B #Cross

array([[20, 14],
       [56, 41],
       [92, 68]])

In [81]:
B.T #

array([[6, 4, 2],
       [5, 3, 1]])

In [82]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
B.T@A

array([[36, 48, 60],
       [24, 33, 42]])

In [85]:
#Sizes of Objects
import sys
sys.getsizeof(1)

28

In [86]:
sys.getsizeof(10**100)

72

In [87]:
np.dtype(int).itemsize

4

In [88]:
np.dtype(float).itemsize

8

In [90]:
#Lsits
sys.getsizeof([1])

64

In [91]:
np.dtype(int).itemsize

4

In [92]:
np.dtype(float).itemsize

8

In [103]:
#Perfomance
l = list(range(10000000))
a = np.arange(10000000)

In [104]:
%time np.sum(a**2)

CPU times: total: 31.2 ms
Wall time: 35 ms


-1039031360

In [105]:
%time sum([x**2 for x in l])

CPU times: total: 5.14 s
Wall time: 5.8 s


333333283333335000000

In [106]:
#Other functions

In [ ]:
#Exercises